# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Max
title2: " Tottenham"
email: max@here.com 
description: > # this means to ignore newlines until "baseurl:"
  Just a personal space for me to write up some github projects.
keywords: "blog, C, software, engineering, C++, Linux, Unix, Akamai, SquarePoint"

#google_analytics:

comments: false

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mtottenh

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
theme: minima

#Sass config
sass:
  sass_dir: assets/scss
  style: compressed
#Author Settings
author:
  name: Max Tottenham
  job: Senior Software Engineer
  company: 'Akamai Technologies'
  location: 'London'
  bio: " Currently working for Akamai Technologies."
  email: max@here.com
  github: https://github.com/mtottenh
  linkedin: https://www.linkedin.com/in/max-tottenham-81560486/


plugins:
  - jekyll-feed
  - bourbon
  - jekyll-paginate

navbar:
  - slug : about
    title: About
  - slug : projects
    title: Projects
  - slug : blog
    title: Blog
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
